### ISSUE TITLE
Sync video and IMU data

### ISSUE THREAD

**Issue by Jessseee** [AI-Sensus/label-studio#1]
Look at the possibility to use the label-studio fork to create an interface to sync IMU data.

**Comment by alexanderm0** [comment]
**Work before**
Page consists of custom tags specified in label-studio/label_studio/frontend/src/pages/CreateProject/Config/tags.js

To make custom video timeseries annotation tool interface, create our own custom tag

**Comment by alexanderm0** [comment]
tags.js stores every custom tag in a structure 'OBJECTS' which is imported into Template.js in the same directory. 

Template exports the class 'Template' which parses a certain template for certain tags

Find out where Template is imported and how new tags can be integrated

**Comment by alexanderm0** [comment]
Tags defined in LSF (Label Studio Frontend) => clone and change fetch to fork, modify components in LSF fork

**Comment by RobvdDuim** [comment]
This will be postponed. For the MVP it is sufficient to ask the user to input the offset between two sensors in a form. See #50
