### ISSUE TITLE
Fix the flaws found by going through complete process

### ISSUE THREAD

**Issue by RobvdDuim** [AI-Sensus/label-studio#138]
- [x] Offset should be per project. Also user should only be able to select sensors from project
- [x] When adding sensordata, user should only be able to select sensors from project 
- [x] Unique subject name check
- [x] When generating activ. annot.  tasks, user should only be able to select subejct from project 
- [x] Fix link that goes to activity annotation project (id=project.id +2)

**Comment by EriktHove** [comment]
- [ ] Generate activity annotation tasks gives error when subject presence is not yet annotated (should warn that user first has to do that)

**Comment by EriktHove** [comment]
Should Deployment link on the project page return error if user has not yet added subjects and sensors?

**Comment by EriktHove** [comment]
- [ ] Delete project does not show warning
- [ ] creating subject annotation labels should also show loading warning
