### ISSUE TITLE
Create method for concatenating annotations per chunk to annotations per uploaded file

### ISSUE THREAD

**Issue by RobvdDuim** [AI-Sensus/label-studio#145]
The data uploaded intended for activity annotation is cut up into data chunks for more manageable tasks. Each chunk becomes a task and gets annotated. The annotations then get stored per task (so per chunk). For our application to be useful for machine learning the annotations should be exportable per uploaded file. Therefore we must concatenate our annotations per chunk into 1 annotations per uploaded (original) file.

For now, there are two options. Using the classes Task and Annotation from LS or using the JSONs generated by exporting each of the annotations per data chunk task

**Comment by EriktHove** [comment]
subject_annotation folder:
- [ ] Find data =>Sensordata(project=project_dataimport).file_upload_project2 != None 
- [ ] Modify video_url in data field of JSON to delete the folders from the file path
- [ ] Put data and annotation JSON in folder

activity_annotation folder:
- [ ] Find data chunks in data_import project => (Look in name generation files)
- [ ] Modify video_url in data field of JSON to delete the folders from the file path
- [ ] Put data and annotation JSON in folder
