### ISSUE TITLE
Change sensor_id to parsable_sensor_id and use it for integrity check on file uploads

### ISSUE THREAD

**Issue by RobvdDuim** [AI-Sensus/label-studio#165]
- [x] change choose sensor.id to sensor.name in add sensor data form
- [x] change sensor.description to sensor.name (unique (required) name)
- [x] use given sensortype to parse the sensor id using column and row value in sensortype config
- [x] remove name field from add sensordata form
- [x] Add integrity check by parsing sensor id when uploading SensorData for data with Sensortype.sensor_column is not null. If ids not the same, give warning

**Comment by RobvdDuim** [comment]
1. Choose sensortype
2. If sensortype.sensor_column is null
3. User selects id self
4. if not sensortype.sensor_column is null
5. Parse id

**Comment by RobvdDuim** [comment]
Sensor_id should be parsable_sensor_id. This field should not be required.

**Comment by EriktHove** [comment]
should only give warning instead of just skipping file
