### ISSUE TITLE
Build first prototype for pre-processing data to create Label Studio annotation tasks

### ISSUE THREAD

**Issue by Jessseee** [AI-Sensus/label-studio#2]
- [x] Make revised design of flow of complete process
- [x] Convert subject presence annotation output from json into django object
- [x] Find overlap between subject presence and IMU data presence
- [x] Crete video chunks (files) and IMU data chunks (files) according with length x
- [x] Create LS JSON tasks that refers to these files
- [x] Create task generation page

For more detailed to do list of the remaining tasks see below

**Comment by RobvdDuim** [comment]
Usefull for annotation template creation:

https://labelstud.io/guide/ts+video.html

**Comment by RobvdDuim** [comment]
Finding overlap is done, but not yet fully tested because of time. See task-generation branch

**Comment by RobvdDuim** [comment]
For task creation one can create a JSON containing the url of the imu data (.csv) and the video (.mp4). For more information, see: https://labelstud.io/guide/ts+video.html

**Comment by RobvdDuim** [comment]
The imu-video trick mentioned twice above will be used, for this we need to downgrade to 1.4.1 (#114).
