### ISSUE TITLE
Annotate videos with subject presence

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#23]
In order to keep track of what subject is present in which video, we need to annotate the videos as a first step (before making the annotation tasks that combine video with IMU data). 

- [x] Investigate label/annotation structure of labelstudio.  we should look at the structure for a default segmenting video task. 
- [x] Create default subject annotation template
- [x] Investigate annotation backend (how are they stored)
- [x] Upload video to labelstudio instance
- [x] Create tasks per video (or video segments if needed performance-wise)
- [x] Annotate a number of videos (use time-adjusted videos on google drive)

**Comment by RobvdDuim** [comment]
Default maximum total size of all files is 250mb. Can be adjusted in the core settings

**Comment by RobvdDuim** [comment]
import json
import requests

from datetime import datetime
from typing import Optional

def json_operations_solution() -> None:
   # From Python object to JSON.
   ocean = {"ocean": "Pacific", "blue": [1, 2, 3, 4]}
   json_ocean = json.dumps(ocean)
   print(json_ocean)

   # From JSON to Python object.
   json_foo_bar = '{ "foo": 1, "bar": [10, "apples"] }'
   foo_bar = json.loads(json_foo_bar)
   print(json.dumps(foo_bar))
