### ISSUE TITLE
[BUG] Videos for synchronization annotation not working

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#270]
I started with a clean install (deleted folder in apps data and pulled new project from repo). I followed the steps as described in technical documentation. There were some hiccups which I commented in the [technical documentation](https://docs.google.com/document/d/1wZqDVggGSPIGmGzrw-ybtJxu57P3KsjQduB4_jPM4HI/edit). 

1. I added a camera

![Image](https://github.com/AI-Sensus/label-studio/assets/10651664/9f929924-d85d-4221-827c-4447b9d5e485)

2. I added an IMU sensor

![Image](https://github.com/AI-Sensus/label-studio/assets/10651664/2e68259c-62b3-4ea6-9bd3-366fb8857e2a)

3. Subject, and deployment. 

![Image](https://github.com/AI-Sensus/label-studio/assets/10651664/4d88bdb9-bda6-4ba7-8b11-3ddc6704a26e)

![Image](https://github.com/AI-Sensus/label-studio/assets/10651664/be02a2c0-5b68-4e0a-8801-5c3a4607b41e)

4. I uploaded a video and IMU file for synchronization (get files here: https://gofile.me/70J3M/5rNmnpgex)
5. I looked at the dates denoted in the data page to make sure the camera time settings were correct 
![Image](https://github.com/AI-Sensus/label-studio/assets/10651664/bb04529d-21d4-4596-84cf-e015edd78c72)

4.Note that the start and end time for the same data file are different on this page: 

![Image](https://github.com/AI-Sensus/label-studio/assets/10651664/0787e09c-f500-47a3-8921-d10db3f69414)

5.  I created an offset annotation task. A black empty video is created.

**Comment by RobvdDuim** [comment]
I repeated the steps. This is what I get on the sensor synchronization screen:


![Image](https://github.com/AI-Sensus/label-studio/assets/105631641/df209bc8-7ec7-4161-baba-ad753fb272c3)

It looks like the -1 hour manual offset is not necessary. So I adjust it to 0:


![Image](https://github.com/AI-Sensus/label-studio/assets/105631641/2ecbf1a4-1249-4b03-b370-fb76a61e0eea)


Now I select the two files and generate the following annotation task:


![Image](https://github.com/AI-Sensus/label-studio/assets/105631641/2b81adfc-1611-4db7-8056-a78a1980ee72)


It seems to work fine. Just to make sure. You deleted the sqlite db, you migrated, you created a new project?

**Comment by RobvdDuim** [comment]
If I add three zeros to the manual offset, which can be seen as switch to milliseconds to seconds: i get the same value as you.


![Image](https://github.com/AI-Sensus/label-studio/assets/105631641/d4688294-076e-47b4-966f-c33f456c3724)

This was something that was committed but the error was taken out in the review. Somehow you pulled the earlier commit. Hope this helps

**Comment by RobvdDuim** [comment]
You are right that if there is no overlap no video should be made, this can be adjusted
