### ISSUE TITLE
Add sensor data parsing for videos

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#41]
Use video import function from old project. We should be able to use the 'old' function and use it to handle all video types in this project

**Comment by jacob-kamminga** [comment]
Import videos and extract metadata

**Comment by RobvdDuim** [comment]
Create unique hash for each file, this way you can check if the file is already uploaded

**Comment by RobvdDuim** [comment]
Final step in #48 (for Erik)
