### ISSUE TITLE
Use #28 to annotate example video (from our Gdrive)

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#56]

**Comment by RobvdDuim** [comment]
[
  {
    "id": 4,
    "annotations": [
      {
        "id": 1,
        "completed_by": 1,
        "result": [
          {
            "original_length": 140.4976,
            "value": {
              "start": 2.2018494065345853,
              "end": 6.350125338320802,
              "channel": 0,
              "labels": [
                "Subject: A",
                " Subject: B"
              ]
            },
            "id": "wavesurfer_v97t10bm5j8",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 6.350125338320802,
              "end": 15.154629356805835,
              "channel": 1,
              "labels": [
                "Subject: A",
                " Subject: B"
              ]
            },
            "id": "wavesurfer_qfe973aaps",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 14.985311971834966,
              "end": 23.959133375290865,
              "channel": 0,
              "labels": [
                "Subject: A",
                " Subject: B"
              ]
            },
            "id": "wavesurfer_65o8gce7nu",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 23.705157297834564,
              "end": 34.20283516602826,
              "channel": 1,
              "labels": [
                "Subject: A",
                " Subject: B",
                " Subject: C"
              ]
            },
            "id": "wavesurfer_tvtrk6lfk7o",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 34.45681124348456,
              "end": 53.84365182264871,
              "channel": 0,
              "labels": [
                "Subject: A",
                " Subject: B"
              ]
            },
            "id": "wavesurfer_tj0f0p4nb9g",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 54.43626267004674,
              "end": 65.69586877060932,
              "channel": 1,
              "labels": [
                " Subject: C"
              ]
            },
            "id": "wavesurfer_39ppsckhlf8",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 65.35723400066759,
              "end": 73.39980978678372,
              "channel": 0,
              "labels": [
                "Subject: A",
                " Subject: B",
                " Subject: C"
              ]
            },
            "id": "wavesurfer_rr4tok7liao",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 73.23049240181287,
              "end": 85.6753201971715,
              "channel": 1,
              "labels": [
                "Subject: A",
                " Subject: B"
              ]
            },
            "id": "wavesurfer_8jpsa04jp88",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 85.50600281220065,
              "end": 92.70199167346246,
              "channel": 0,
              "labels": [
                "Subject: A",
                " Subject: B",
                " Subject: C"
              ]
            },
            "id": "wavesurfer_8b1pfcfjgv8",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          },
          {
            "original_length": 140.4976,
            "value": {
              "start": 96.00368068039434,
              "end": 140.33405055266604,
              "channel": 0,
              "labels": [
                "Subject: A",
                " Subject: B",
                " Subject: C"
              ]
            },
            "id": "wavesurfer_ivtgl7dklf8",
            "from_name": "subjects",
            "to_name": "audio",
            "type": "labels",
            "origin": "manual"
          }
        ],
        "was_cancelled": false,
        "ground_truth": false,
        "created_at": "2023-04-04T15:22:53.110664Z",
        "updated_at": "2023-04-04T15:22:58.030523Z",
        "lead_time": 232.818,
        "prediction": {},
        "result_count": 0,
        "unique_id": "2108b538-0a73-4807-973e-558462023a8f",
        "last_action": null,
        "task": 4,
        "project": 5,
        "updated_by": 1,
        "parent_prediction": null,
        "parent_annotation": null,
        "last_created_by": null
      }
    ],
    "file_upload": "056238c2-26o3soo7.upload.mp4",
    "drafts": [],
    "predictions": [],
    "data": {
      "video_url": "/data/upload/5/056238c2-26o3soo7.upload.mp4"
    },
    "meta": {},
    "created_at": "2023-04-04T15:18:44.530871Z",
    "updated_at": "2023-04-04T15:22:58.074862Z",
    "inner_id": 1,
    "total_annotations": 1,
    "cancelled_annotations": 0,
    "total_predictions": 0,
    "comment_count": 0,
    "unresolved_comment_count": 0,
    "last_comment_updated_at": null,
    "project": 5,
    "updated_by": 1,
    "comment_authors": []
  }
]

**Comment by RobvdDuim** [comment]
The comment above is the subject annotation of the video: https://drive.google.com/file/d/1-YgfM3n_wIaT7ZdcEEUq2x9uD_t1R7bD/view?usp=share_link
