### ISSUE TITLE
Process bundled (zip) data upload

### ISSUE THREAD

**Issue by EriktHove** [AI-Sensus/label-studio#77]
- [x] Create function to unpack zip file. Should iterate over folders recursively (process subfolders)
- [x] Parse csv files and import when valid
- [x] Extract meta data from video files and store videos

See Flowchart for design (for now not necessary)
Update Flowchart

**Comment by RobvdDuim** [comment]
- Only for sensors that have metadata in .csv file
- User uploads .zip file
- For every file check if date is an actual date (if not throw exception)

**Comment by EriktHove** [comment]
Should be independent of folder structure

**Comment by EriktHove** [comment]
what seemed to work for the migration issues in the sensordata_sensordata database was deleting all the migration files (except the init file) in the sensordata app. (Watch the dependencies here) 

Then I created a new migration file using 'python label_studio/manage.py makemigrations

That at first didnt work so I used the command
python label_studio/manage.py migrate sensordata zero
python label_studio/manage.py migrate

This did the trick
