### ISSUE TITLE
Look into creating task with video and csv files

### ISSUE THREAD

**Issue by RobvdDuim** [AI-Sensus/label-studio#82]

**Comment by jacob-kamminga** [comment]
Are multiple files supported?

**Comment by RobvdDuim** [comment]
https://labelstud.io/guide/ts+video.html
https://github.com/AI-Sensus/Experiments/issues/15

**Comment by RobvdDuim** [comment]
For task creation one can create a JSON containing the url of the imu data (.csv) and the video (.mp4). For more information, see: https://labelstud.io/guide/ts+video.html

**Comment by RobvdDuim** [comment]
There has been chosen to use the csv+mp4 syncs trick proposed above. This created issue: #114
