### ISSUE TITLE
Refine landing page

### ISSUE THREAD

**Issue by jacob-kamminga** [AI-Sensus/label-studio#84]

**Comment by jacob-kamminga** [comment]
- [ ] Rename step 6 to Annotate subsect presence
- [ ] Fix URL of step 5 
- [ ] Direct URL of step 6 to go to the tasks_overview of PROJECTNAME_ANNOTATESUBJECTPRESENCE

**Comment by EriktHove** [comment]
The step 6 problems are fixed in the improve-subject-annotation branch

**Comment by EriktHove** [comment]
The step 5 issue is because of migration issues, so it works now in my branch but maybe check again after merging to aisensus-develop
