### ISSUE TITLE
Create homepage where user can select the project

### ISSUE THREAD

**Issue by RobvdDuim** [AI-Sensus/label-studio#94]
Right now the landing page is not linked to a project. This has to change to a landing page being linked to a project. This way we can navigate the user through all the steps, without it seeing the projects page of LS. In order for this to work two things need to happen. 1. Create homepage for navigating through AISensus projects. 2. Make landing pages linked to projects.

**Homepage**
Create homepage.html in landing page app.  Here the user can select a project based on the name chosen in the beginning. So, it doesn't see the three projects we create in the backend, but just one with name. For display I think putting all the project names in a table with a go to landing page link (like we did with adjust and delete sensor etc.) is the best way, for now.
- [x] Create homepage.html with table for name + go to landingpage link
- [x] Create method that reads all project names (using LS list projects API) and gets unique name + project.id of data_import project
- [x] Create view method that gets names + project.id's. It uses this to render homepage.html and fill the table
- [x] Implement delete functionality for projects. It should delete all three subprojects when called upon.

**Link landing pages to projects**
- [x] Adjust the landing page url to path('<int:project>', views.landingpage, name = 'landingpage')
- [x] Adjust landingpage.html so that the  h1 has the name of the project selected. And adjust the <a> so that they point to the correct project (for example got to the subject annotation project or go to the manage labels in the activity annotation project from #88) This cannot happen yet since the correct versions of the annotation pages are not yet applied in aisensus-develop.
- [x] Change landingpage() so that it also takes in an integer of the project id. It feeds this project id into 'landingpage.html'

Lastly, Subject and Sensor will be linked to projects instead of being available for all projects
- [x] Add (FK) project to Subject and sensor

**Comment by EriktHove** [comment]
- [ ] Objects should only be visible in assigned projects
- [ ] Subjectannotation page should redirect to subjectannotation labeling
- [ ] Export page should download directly or redirect to homepage

**Comment by EriktHove** [comment]
- [ ] deployment shows all subjects, sensors in form
